#pragma kernel CSMain
#include "NoiseBase.compute"


RWStructuredBuffer<float4> Result;
RWStructuredBuffer<float3> octaveOffsets;
int3 size;
float scale;
float persistance;
float lacunarity;
float noiseExtents;
float vertDistance;
float3 worldOffset;
int octaves;
int3 worldChunk;
int3 maxChunk;
float distanceFactor;
float groundHeight;
float isoLevel;
float amplitude;

float RoundToOneDecimalPlace(float value)
{
    return round(value * 10.0) / 10.0;
}

#define THREAD 8

[numthreads(THREAD, THREAD, THREAD)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)size.x || id.y >= (uint)size.y || id.z >= (uint)size.z)
    {
        return;
    }
    float localX = id.x * vertDistance;
    float localY = id.y * vertDistance;
    float localZ = id.z * vertDistance;

    float worldY = ((worldChunk.y * (size.y - 1)) * vertDistance) + localY;
    float maxY = ((maxChunk.y * (size.y - 1)) * vertDistance);

    float frequency = 1.0f;
    float noiseHeight = 0.0f;
    float amp = amplitude;

    for (int i = 0; i < octaves; i++)
    {
        float3 sample = (float3(id) / scale + octaveOffsets[i]) * frequency;
        noiseHeight += cnoise(sample) * amp;
        amp *= persistance;
        frequency *= lacunarity;
    }
    float hDelta = InverseLerp(groundHeight, maxY, worldY);
    noiseHeight = InverseLerp(-noiseExtents, noiseExtents, noiseHeight);
    float4 outputValue = float4(localX, localY, localZ, (hDelta + noiseHeight) / 2);

    Result[id.x + id.y * size.x + id.z * size.x * size.y] = outputValue;
}
